version: '3'
services:
  web:
    build: ./infer-app
    image: infer-app
    ports:
      - '50000:50000'
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always


volumes:
    redis_data:
      driver: local