apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/2-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - redis-server
            - --save
            - "20"
            - "1"
            - --loglevel
            - warning
          image: redis:alpine
          name: redis
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
