apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.network/2-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: infer-app
          imagePullPolicy: Never
          name: web
          ports:
            - containerPort: 50000
              hostPort: 50000
              protocol: TCP
      restartPolicy: Always
