apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "50000"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: web
